if __name__ == '__main__':
    from agent import Agent
    agent = Agent()
    agent.learn()
    agent.learn()
    agent.learn()
    agent.learn()
    agent.learn()
    agent.learn()
    agent.learn()
    agent.learn()
    agent.learn()
    agent.learn()
    agent.learn()
    agent.learn()
    agent.learn()
    agent.learn()
    agent.learn()
    agent.learn()
    agent.learn()
    agent.learn()
    agent.learn()
    agent.learn()
    agent.learn()
    agent.learn()
    agent.learn()
    agent.learn()
    agent.learn()
    agent.learn()
    agent.learn()
    agent.learn()
    agent.learn()
    agent.learn()
    agent.learn()
    agent.learn()
    agent.learn()
    agent.learn()
    agent.learn()
    agent.learn()
    agent.learn()
    agent.learn()
    agent.learn()
    agent.learn()
    agent.learn()
    agent.learn()
    agent.learn()
    agent.learn()
    agent.learn()
    for key in agent.qvalues:
        if agent.qvalues[key] != 0.:
            state, action = key
            print str(state) + ", " + str(action) + ": " + str(agent.qvalues[key])
